### ISSUE TITLE
Sunmi Device P2 not support

### ISSUE THREAD

**Issue by Kimsoer** [nfcim/flutter_nfc_kit#146]
Dear team, Thank you so much for your great library, I have issue to use it with sunmi device p2 and p2 pro, I try to use it for checking nfc but it response not support, Is it possible to use it with sunmi device, thank you

**Comment by dangfan** [comment]
Thank you for your feedback and for using our library. It's important to note that these devices do not use the standard Android NFC interface. As a result, they require specific development based on the manufacturer's documentation. Unfortunately, this means that our library does not support these devices due to their unique implementation.

**Comment by Kimsoer** [comment]
Oh , I got it thank you so much @dangfan
