### ISSUE TITLE
Can ı send data to another device using nfc?

### ISSUE THREAD

**Issue by alidemircans** [nfcim/flutter_nfc_kit#49]

**Comment by dangfan** [comment]
flutter_nfc_kit does not provide P2P mode because iPhone does not support this mode.
If you're targeting Android applications, please refer to https://developer.android.com/guide/topics/connectivity/nfc.

If you're going to send data to devices other than mobile phones, it is possible that you can use a simulated card so that any mobile phone can communicate with it.
