### ISSUE TITLE
Signature process

### ISSUE THREAD

**Issue by ethicnology** [nfcim/flutter_nfc_kit#99]
Hi I'm desperately trying to find a flutter example for a SECP256K1/SHA256 digital signature using a compatible NFC card.

Do you have an example of signature record ?
(I give a hash and the card sign it and return the signature)

**Comment by dangfan** [comment]
Hi, the protocols related to SECP256K1/SHA256 digital signatures, especially when interfacing with NFC cards, are often proprietary. I would recommend referring to the specific manual or documentation of the NFC card you are using. This issue is not directly related to Flutter. It's more about the card's capabilities and its proprietary protocols.
